name: CI/CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: aws-devops-demo/app
        run: npm ci || npm install

      - name: Run tests
        working-directory: aws-devops-demo/app
        run: npm test

  terraform_apply:
    runs-on: ubuntu-latest
    needs: build_and_test
    defaults:
      run:
        working-directory: aws-devops-demo/iac
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Verify EC2 key pair exists in ap-south-1
        run: |
          aws ec2 describe-key-pairs \
            --key-names "${{ secrets.AWS_KEY_PAIR_NAME }}" \
            --region ap-south-1 \
            --output json > /tmp/keypair.json
          cat /tmp/keypair.json

      - name: Terraform Init
        run: terraform init -input=false -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: |
          terraform plan -input=false -no-color -out=tfplan \
            -var "repo_url=https://github.com/${{ github.repository }}.git" \
            -var "key_name=${{ secrets.AWS_KEY_PAIR_NAME }}" \
            -var "aws_region=ap-south-1"

      - name: Show Plan (debug)
        run: terraform show -no-color tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -no-color -auto-approve tfplan



