name: CI/CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: aws-devops-demo/app
        run: npm ci || npm install

      - name: Run tests
        working-directory: aws-devops-demo/app
        run: npm test

  terraform_apply:
    runs-on: ubuntu-latest
    needs: build_and_test
    defaults:
      run:
        working-directory: aws-devops-demo/iac
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var "repo_url=https://github.com/${{ github.repository }}.git" \
            -var "key_name=${{ secrets.AWS_KEY_PAIR_NAME }}" \
            -var "aws_region=ap-south-1"


